# Buildpack API version
api = "0.5"

# Buildpack ID and metadata
[buildpack]
id = "dirigiblelabs/kneo-java-buildpack"
version = "0.0.1"
name = "Kneo Java Buildpack"

# Stacks that the buildpack will work with
[[stacks]]
id = "com.sap.kneo.java"
