apiVersion: kpack.io/v1alpha1
kind: ClusterStore
metadata:
  name: kneo-xsk-store
spec:
  sources:
  - image: dirigiblelabs/kneo-xsk-buildpack:<tag>
---
apiVersion: kpack.io/v1alpha1
kind: ClusterStack
metadata:
  name: kneo-xsk-stack
spec:
  id: "com.sap.kneo.xsk"
  buildImage:
    image: "dirigiblelabs/kneo-xsk-stack-build:<tag>"
  runImage:
    image: "dirigiblelabs/kneo-xsk-stack-run:<tag>"
---
apiVersion: kpack.io/v1alpha1
kind: Builder
metadata:
  name: kneo-xsk
spec:
  serviceAccount: docker-registry-service-account
  tag: dirigiblelabs/kneo-xsk-builder:<tag>
  stack:
    name: kneo-xsk-stack
    kind: ClusterStack
  store:
    name: kneo-xsk-store
    kind: ClusterStore
  order:
  - group:
    - id: dirigiblelabs/kneo-xsk-buildpack
