name: Pull Request

on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Download sapmachine JDK 11
      run: |
        download_url="https://github.com/SAP/SapMachine/releases/download/sapmachine-11.0.11%2B8/sapmachine-jdk-11.0.11-ea.8_linux-x64_bin.tar.gz"
        wget -O "${RUNNER_TEMP}/sapmachine-jdk-11.0.11.tar.gz" "${download_url}"
    - name: Setup sapmachine JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'jdkfile'
        jdkFile: ${{ runner.temp }}/sapmachine-jdk-11.0.11.tar.gz
        java-version: '11.0.11'
        architecture: x64
    - name: Maven Build
      run: mvn clean install
    - name: Docker Build XSK
      run: |
        cd releng/server
        cp -r "${JAVA_HOME}" jdk
        docker build -t dirigiblelabs/xsk --build-arg JDK_TYPE=external-jdk --build-arg JDK_HOME=jdk .
        cd ../../
    - name: Docker Build XSK for SAP Cloud Foundry
      run: |
        cd releng/sap-cf
        cp -r "${JAVA_HOME}" jdk
        docker build -t dirigiblelabs/xsk-cf --build-arg JDK_TYPE=external-jdk --build-arg JDK_HOME=jdk .
        cd ../../
    - name: Docker Build XSK for SAP Kyma
      run: |
        cd releng/sap-kyma
        cp -r "${JAVA_HOME}" jdk
        docker build -t dirigiblelabs/xsk-kyma --build-arg JDK_TYPE=external-jdk --build-arg JDK_HOME=jdk .
        cd ../../
    - uses: buildpacks/github-actions/setup-pack@v4.1.0
    - name: XSK Buildpack
      run: |
        cd releng/buildpacks/xsk/
        docker build -t dirigiblelabs/kneo-xsk-stack-base . --target base
        docker build -t dirigiblelabs/kneo-xsk-stack-run . --target run
        docker build -t dirigiblelabs/kneo-xsk-stack-build . --target build
        cd buildpack/
        pack buildpack package dirigiblelabs/kneo-xsk-buildpack --config ./package.toml
        cd ../../../../
    - name: Java Buildpack
      run: |
        cd releng/buildpacks/java/
        docker build -t dirigiblelabs/kneo-java-stack-base . --target base
        docker build -t dirigiblelabs/kneo-java-stack-run . --target run
        docker build -t dirigiblelabs/kneo-java-stack-build . --target build
        cd buildpack/
        pack buildpack package dirigiblelabs/kneo-java-buildpack --config ./package.toml
        cd ../../../../
